//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiabeticSystem.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientMembershipDetail
    {
        public int MembershipId { get; set; }
        public int PatientId { get; set; }
        public int TestRemaining { get; set; }
        public System.DateTime BookedDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
    
        public virtual PatientPersonal PatientPersonal { get; set; }
    }
}
