//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiabeticSystem.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientTestResult
    {
        public int TestId { get; set; }
        public int PatientId { get; set; }
        public int SugarBeforeFasting { get; set; }
        public int SugarAfterFasting { get; set; }
        public Nullable<System.DateTime> TestDate { get; set; }
    
        public virtual PatientPersonal PatientPersonal { get; set; }
    }
}
